### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by ircer** [pavben/WebIRC#27]
```
root@li646-175:~/WebIRC# npm start

> WebIRC@0.0.1 start /root/WebIRC
> babel-node main.js

error: Failed to start WebIRC: Error: ENOENT, scandir '/root/WebIRC/users'

npm ERR! Linux 4.1.0-x86_64-linode59
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! WebIRC@0.0.1 start: `babel-node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WebIRC@0.0.1 start script 'babel-node main.js'.
npm ERR! This is most likely a problem with the WebIRC package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls WebIRC
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WebIRC/npm-debug.log
root@li646-175:~/WebIRC# 
```

**Comment by pavben** [comment]
See step #5 of the README at https://github.com/pavben/WebIRC. It looks like your "users" dir doesn't exist.

**Comment by ircer** [comment]
@pavben sorry about that.

Basically I have a 100% webchat site that gets a great deal of traffic (around 500 users connected via our current webchat at a time).

Current problem is the webchat that we use is closed source and looks ugly (it looks completely out of place compared to our main site CSS).

We don't have any user registrations or such (hence why I didn't bother with that step). Basically this is great (even better that it's not Flash, as that limits our reach considerably on mobiles etc.).

How much work would it be so that I can use it like we do with out existing webchat?

Our webchat at the moment gets its user settings from `$_POST` data from our main site:

```
// load webchat
params.nickname = "<?php echo $_POST['nickname']; ?>";
params.ident = "<?php echo $_POST['gender'];";
params.realname = "Flash IRC client";
```

Do you think something similar is possible?

Awesome work!

**Comment by pavben** [comment]
It's not really intended to be used as a webchat, but rather as a complete IRC client that stays connected to all your servers. If you wanted to spawn on-demand instances, you'd need to write a script that would generate the config for this user and run that instance and then redirect the user to it. Still, that allows them to use your server's IP to connect anywhere they like, so you'd basically end up with having to fork the code and restrict this functionality (use of /server). It also won't scale to too many users since each user would have their own instance.

I think you'd have more luck finding something designed for your purpose, but feel free to experiment if you have the time :)
